//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greens.GreensService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GreensPrice", Namespace="http://schemas.datacontract.org/2004/07/GreensService")]
    [System.SerializableAttribute()]
    public partial class GreensPrice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GreensService.IGreensService")]
    public interface IGreensService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreensService/ConvertDataToGreensPrice", ReplyAction="http://tempuri.org/IGreensService/ConvertDataToGreensPriceResponse")]
        Greens.GreensService.GreensPrice ConvertDataToGreensPrice(string name, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreensService/ConvertDataToGreensPrice", ReplyAction="http://tempuri.org/IGreensService/ConvertDataToGreensPriceResponse")]
        System.Threading.Tasks.Task<Greens.GreensService.GreensPrice> ConvertDataToGreensPriceAsync(string name, int price);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGreensServiceChannel : Greens.GreensService.IGreensService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GreensServiceClient : System.ServiceModel.ClientBase<Greens.GreensService.IGreensService>, Greens.GreensService.IGreensService {
        
        public GreensServiceClient() {
        }
        
        public GreensServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GreensServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreensServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreensServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Greens.GreensService.GreensPrice ConvertDataToGreensPrice(string name, int price) {
            return base.Channel.ConvertDataToGreensPrice(name, price);
        }
        
        public System.Threading.Tasks.Task<Greens.GreensService.GreensPrice> ConvertDataToGreensPriceAsync(string name, int price) {
            return base.Channel.ConvertDataToGreensPriceAsync(name, price);
        }
    }
}
